import numpy as np


BYTE_DTYPE = np.uint8
INTEGER_DTYPE = np.int16
UNSIGNED_INTEGER_DTYPE = np.uint16
FLOAT_DTYPE = np.float32
MAX_INT = np.iinfo(INTEGER_DTYPE).max
MAX_UINT = np.iinfo(UNSIGNED_INTEGER_DTYPE).max


# only 32bit, 24bit no alpha, or 8bit pallete
SURFACE_MODE = "RGBA"
SCREEN_WIDTH = 320
SCREEN_HEIGHT = 240
SCREEN_ASPECT_RATIO = SCREEN_WIDTH / SCREEN_HEIGHT
NUM_SCRATCH_BUFFERS = 32
SCRATCH_BUFFER_SIZE = MAX_UINT

SCREEN_HALF_WIDTH = SCREEN_WIDTH // 2
SCREEN_HALF_HEIGHT = SCREEN_HEIGHT // 2

SCREEN_HALF_SIZE = np.array([SCREEN_HALF_WIDTH, SCREEN_HALF_HEIGHT])